// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthxaawazqeexzdelacz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aHhhYXdhenFlZXh6ZGVsYWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDI0ODksImV4cCI6MjA3MjIxODQ4OX0.b74bwQD5dAqyMSfuaMQY5Pzc9GHaGRW9uT3fLE3pRbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});